platform :ios, '14.0'

target 'ProjetoDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetoDesign
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  target 'ProjetoDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoDesignUITests' do
    # Pods for testing
  end

end
