platform :ios, '14.0'

target 'ProjetoDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetoDesign
  pod 'IQKeyboardManagerSwift', '~> 6.3'
  pod 'Alamofire', '~> 5.2'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 5.0'
  pod 'PKHUD'
  pod 'ReachabilitySwift'
  pod 'SwiftMessages'
  pod 'CircleBar'
  pod 'GoogleSignIn'
  pod 'MaterialComponents'
  pod 'FBSDKLoginKit'
  pod 'SwiftyCam'
  pod 'SegmentedProgressView'
  pod 'SwiftGifOrigin'

  target 'ProjetoDesignTests' do
    inherit! :search_paths

    pod 'Nimble-Snapshots'
    pod 'KIF'
    pod 'KIF/IdentifierTests'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
